### ISSUE TITLE
T11SeleniumChronosDiffTest does not work

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/materialstore-tutorial#10]
I ran `my.sample.T11SeleniumChronosDiffTest`

https://github.com/kazurayam/materialstore-tutorial/commit/86402066f6659235918cfef7f40f2d7fb18b9bf0

and saw

```
Starting Gradle Daemon...
Gradle Daemon started in 1 s 855 ms

> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava UP-TO-DATE
> Task :processTestResources UP-TO-DATE
> Task :testClasses UP-TO-DATE
> Task :test
[Test worker] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 113.0.5672.63 (resolved driver for Chrome 113)
[Test worker] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /Users/kazuakiurayama/.cache/selenium/chromedriver/mac64/113.0.5672.63/chromedriver
Starting ChromeDriver 113.0.5672.63 (0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}) on port 22356
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
5月 23, 2023 7:30:51 午前 org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
警告: Unable to find CDP implementation matching 113
5月 23, 2023 7:30:52 午前 org.openqa.selenium.chromium.ChromiumDriver lambda$new$3
警告: Unable to find version of CDP to use for . You may need to include a dependency on a specific version of the CDP using something similar to `org.seleniumhq.selenium:selenium-devtools-v86:4.6.0` where the version ("v86") matches the version of the chromium-based browser you're using and the version number of the artifact is the same as Selenium's.
step0_restorePrevious started
[Test worker] WARN com.kazurayam.inspectus.core.internal.AbstractService - JobName performChronosDiff is not found in the backup store /Users/kazuakiurayama/github/materialstore-tutorial/build/tmp/testOutput/my.sample.T11SeleniumChronosDiffTest/store-backup
step0_restorePrevious finished
BUILD SUCCESSFUL in 22s
3 actionable tasks: 1 executed, 2 up-to-date
7:30:53: Execution finished ':test --tests "my.sample.T11SeleniumChronosDiffTest"'.

```

I saw the message `step0_restorePrevious finished` but stopped. No more steps are performed. Why?

**Comment by kazurayam** [comment]
This issue may have something to do with the following issue in the inspectus project:

https://github.com/kazurayam/inspectus/issues/91

**Comment by kazurayam** [comment]
changed the `performChronosDiff()` slightly.

now I see a StackTrace is printed.

```
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava UP-TO-DATE
> Task :processTestResources UP-TO-DATE
> Task :testClasses UP-TO-DATE
> Task :test
[Test worker] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 113.0.5672.63 (resolved driver for Chrome 113)
[Test worker] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /Users/kazuakiurayama/.cache/selenium/chromedriver/mac64/113.0.5672.63/chromedriver
Starting ChromeDriver 113.0.5672.63 (0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}) on port 6451
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
5月 23, 2023 12:28:11 午後 org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
警告: Unable to find CDP implementation matching 113
5月 23, 2023 12:28:11 午後 org.openqa.selenium.chromium.ChromiumDriver lambda$new$3
警告: Unable to find version of CDP to use for . You may need to include a dependency on a specific version of the CDP using something similar to `org.seleniumhq.selenium:selenium-devtools-v86:4.6.0` where the version ("v86") matches the version of the chromium-based browser you're using and the version number of the artifact is the same as Selenium's.
step0_restorePrevious started
[Test worker] WARN com.kazurayam.inspectus.core.internal.AbstractService - JobName performChronosDiff is not found in the backup store /Users/kazuakiurayama/github/materialstore-tutorial/build/tmp/testOutput/my.sample.T11SeleniumChronosDiffTest/store-backup
step0_restorePrevious finished
step1_restorePrevious started

com.kazurayam.materialstore.core.MaterialstoreException: JobName "performChronosDiff" is not found in /Users/kazuakiurayama/github/materialstore-tutorial/./build/tmp/testOutput/my.sample.T11SeleniumChronosDiffTest/store-backup
com.kazurayam.inspectus.core.InspectusException: com.kazurayam.materialstore.core.MaterialstoreException: JobName "performChronosDiff" is not found in /Users/kazuakiurayama/github/materialstore-tutorial/./build/tmp/testOutput/my.sample.T11SeleniumChronosDiffTest/store-backup
	at app//com.kazurayam.inspectus.core.internal.ChronosDiff.step1_restorePrevious(ChronosDiff.java:62)
	at app//com.kazurayam.inspectus.core.internal.ChronosDiff.process(ChronosDiff.java:37)
	at app//com.kazurayam.inspectus.core.Inspectus.execute(Inspectus.java:11)
	at app//my.sample.T11SeleniumChronosDiffTest.performChronosDiff(T11SeleniumChronosDiffTest.java:100)
	at java.base@11.0.18/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.18/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.18/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.18/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at app//org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at app//org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at app//org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at app//org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at app//org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base@11.0.18/java.util.ArrayList.forEach(ArrayList.java:1541)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base@11.0.18/java.util.ArrayList.forEach(ArrayList.java:1541)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at app//org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:110)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:85)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base@11.0.18/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.18/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.18/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.18/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: com.kazurayam.materialstore.core.MaterialstoreException: JobName "performChronosDiff" is not found in /Users/kazuakiurayama/github/materialstore-tutorial/./build/tmp/testOutput/my.sample.T11SeleniumChronosDiffTest/store-backup
	at app//com.kazurayam.materialstore.core.StoreImpl.findAllJobTimestamps(StoreImpl.java:198)
	at app//com.kazurayam.materialstore.core.StoreImpl.findLatestJobTimestamp(StoreImpl.java:340)
	at app//com.kazurayam.materialstore.base.manage.StoreImportImpl.importReports(StoreImportImpl.java:30)
	at app//com.kazurayam.inspectus.core.internal.ChronosDiff.step1_restorePrevious(ChronosDiff.java:55)
	... 87 more


T11SeleniumChronosDiffTest > performChronosDiff() FAILED
    com.kazurayam.inspectus.core.InspectusException at T11SeleniumChronosDiffTest.java:100
        Caused by: com.kazurayam.materialstore.core.MaterialstoreException at T11SeleniumChronosDiffTest.java:100
1 test completed, 1 failed
> Task :test FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/kazuakiurayama/github/materialstore-tutorial/build/reports/tests/test/index.html
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 6s
3 actionable tasks: 1 executed, 2 up-to-date


```

**Comment by kazurayam** [comment]
In T11SeleniumChronosDiffTest
```
@Test
    public void performChronosDiff() throws InspectusException {
        try {
            Parameters parameters = new Parameters.Builder()
                    .store(Stores.newInstance(outputDir.resolve("store")))
                    .backup(Stores.newInstance(outputDir.resolve("store-backup")))
                    .jobName(new JobName("performChronosDiff"))
                    .jobTimestamp(JobTimestamp.now())
                    .sortKeys(new SortKeys("step"))
                    .threshold(1.0)
                    .build();
            Inspectus chronosDiff = new FnChronosDiff(fn);
            chronosDiff.execute(parameters);
        } catch (InspectusException e) {
            if (e.getMessage().contains("previousMaterialList of size == 0")) {
                logger.warn("chronosDiff.execute() failed because the backup-store was empty. Will try again.");
                // do it once more with new JobTimestamp
                Parameters parameters = new Parameters.Builder()
                        .store(Stores.newInstance(outputDir.resolve("store")))
                        .backup(Stores.newInstance(outputDir.resolve("store-backup")))
                        .jobName(new JobName("performChronosDiff"))
                        .jobTimestamp(JobTimestamp.now())
                        .sortKeys(new SortKeys("step"))
                        .threshold(1.0)
                        .build();
                Inspectus chronosDiff = new FnChronosDiff(fn);
                chronosDiff.execute(parameters);
            } else {
                throw e;
            }
        }
    }
```

Here,  the `performChronosDiff` method tries to detect that there are not directory+files to restore, and if so it tries to execute FnChronosDiff(fn) again.

However the logic is too fragaile. The logic depends on the message text. The message text tends to be changed carelessly. It is not a good idea to depend on the message text.

**Comment by kazurayam** [comment]
Possibly, the inspectus should throw a dedicated type of Excetion, not a generic InspectusException, to distinguish that the required JobName was not found.

```
at com.kazurayam.materialstore.base.manage.StoreImportImpl.importReports(StoreImportImpl.java:30)
```

I have to revise the materialstore library for this.

**Comment by kazurayam** [comment]
updated the materialstore to v0.16.6 and updated the inspectusl to v0.9.6 for this issue

**Comment by kazurayam** [comment]
fixed
